### ISSUE TITLE
课程表数据是否没有更新？

### ISSUE THREAD

**Issue by assault65535** [Hjsmallfly/stu_syllabus#1]
**app 版本 / app version:**
1.4

**操作系统 / OS:**
Android 4.4.4

**详细描述 / Details**
说两个在咱这里见到的和实际数据不同步的地方。
1. 课程 87566 的任课老师已有变动 (从英文名变成了中文名)，但 app 没有跟进。
2. app 显示了我选了课程 88307，但我早已选了课程 88309 取而代之，而 app 仅显示了前者。

**Comment by xiaofud** [comment]
同步一次课表即可，APP默认使用的是之前缓存过的数据~

**Comment by assault65535** [comment]
试过同步，但说是网络连接错误。

**Comment by xiaofud** [comment]
今晚10点后学校服务器流量爆了，现在可以了

**Comment by daidaijie** [comment]
Make sure that your password is correct

**Comment by assault65535** [comment]
感谢解答，问题已解决，麻烦各位了
